textsummarization/news/urls.py
from django.contrib import admin
from django.conf.urls import url,include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^usernews/', include('usersnews.urls')),
]

textsummarization/textsummarization/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^app/',include('text.urls')),
]

textsummarization/usersnews/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from . import views

app_name="usernews"
urlpatterns = [
    url(r'^$', views.index,name='index'),
    url(r'^login/$', views.login,name='login'),
    url(r'^signup/$', views.signup,name='signup'),
    url(r'^homePage/$', views.homePage,name='homePage'),
    
]

textsummarization/templates/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>User Page</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'css/simple-sidebar.css' %}" rel="stylesheet">

</head>

<body>

  <div class="d-flex" id="wrapper">

    <!-- Sidebar -->
    <div class="bg-light border-right" id="sidebar-wrapper">
      <div class="sidebar-heading">News</div>
      <div class="list-group list-group-flush">
        <a href="{% url 'usernews:homePage'%}" class="list-group-item list-group-item-action bg-light">News Content</a>
        <a href="{% url 'usernews:login'%}" class="list-group-item list-group-item-action bg-light">Logout</a>
        
      </div>
    </div>
    <!-- /#sidebar-wrapper -->

    <!-- Page Content -->
    <div id="page-content-wrapper">

      <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
        <button class="btn btn-primary" id="menu-toggle">Toggle Menu</button>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        
      </nav>

     
      
     
      {% block a %}

      {% endblock %}
    
    <!-- /#page-content-wrapper -->

  </div>
  <!-- /#wrapper -->

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'vendor/jquery/jquery.min.js'%}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script>

  <!-- Menu Toggle Script -->
  <script>
    $("#menu-toggle").click(function(e) {
      e.preventDefault();
      $("#wrapper").toggleClass("toggled");
    });
  </script>

</body>

</html>

textsummarization/templates/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login V4</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="{% static 'login/images/icons/favicon.ico' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/fonts/iconic/css/material-design-iconic-font.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/vendor/animate/animate.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'login/vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/vendor/animsition/css/animsition.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'login/vendor/daterangepicker/daterangepicker.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'login/css/main.css' %}">
<!--===============================================================================================-->
</head>
<body>
	
	<div class="limiter">
		<div class="container-login100" style="background-image: url('images/bg-01.jpg');">
			<div class="wrap-login100 p-l-55 p-r-55 p-t-65 p-b-54">
				<form class="login100-form validate-form" method="POST">
					{% csrf_token %}
					<span class="login100-form-title p-b-49">
						Login
					</span>

					<div class="wrap-input100 validate-input m-b-23" data-validate = "Username is reauired">
						<span class="label-input100">Username</span>
						<input class="input100" type="text" name="username" placeholder="Type your username">
						<span class="focus-input100" data-symbol="&#xf206;"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="Password is required">
						<span class="label-input100">Password</span>
						<input class="input100" type="password" name="pass" placeholder="Type your password">
						<span class="focus-input100" data-symbol="&#xf190;"></span>
					</div>
					
					<div class="text-right p-t-8 p-b-31">
						{{A}}
					</div>
					
					<div class="container-login100-form-btn">
						<div class="wrap-login100-form-btn">
							<div class="login100-form-bgbtn"></div>
							<button class="login100-form-btn">
								Login
							</button>
						</div>
					</div>

					<div class="txt1 text-center p-t-54 p-b-20">
						<span>
							<a href="{% url 'usernews:signup'  %}" >Sign Up</a>
						</span>
					</div>

				
					<div class="flex-col-c p-t-155">
						<span class="txt1 p-b-17">
							Or Sign Up Using
						</span>

						<a href="#" class="txt2">
							Sign Up
						</a>
					</div>
				</form>
			</div>
		</div>
	</div>
	

	<div id="dropDownSelect1"></div>
	
<!--===============================================================================================-->
	<script src="{% static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/animsition/js/animsition.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/daterangepicker/moment.min.js' %}"></script>
	<script src="{% static 'vendor/daterangepicker/daterangepicker.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/countdowntime/countdowntime.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'js/main.js' %}"></script>

</body>
</html>

textsummarization/templates/nlcmd.html
{% extends "index.html" %}
{% block a %}
    <div class="container-fluid">
        <form method="POST">
          {% csrf_token %}
          <div class="form-group">
                <label for="email">Command</label>
                <select class="form-control" name="queryId" >
                        {% for al in data %}
                        <option value="{{a.0}}">{{al.1}}</option>
                        
                        {% endfor %}
                </select>
              </div>
            <div class="form-group">
                    <label for="email">User Data</label>
                    <input type="text" required class="form-control" name="NlCMD" id="email">
                  </div>  
             
              
              <button type="submit" class="btn btn-default btn-success">Submit</button>
        </form>
      </div>
      <div class="container-fluid">
            <div class="form-group">
                <label for="email"> {{A}}</label>
                <table class="table">
                    <thead>
                        <tr>
                            <td>Query</td>
                           
                            <td>Delete</td>
                        </tr>
                    </thead>
                    <tbody>
                      {% for al in nltcmd %}
                        <tr>
                          <td>{{al.1}}</td>
                          
                          <td><a href="{% url 'nlpsql:nlremove' al.0 %}">Remove</a></td>
                        </tr>
                      {% endfor %}
                    </tbody>
                  </table>
              </div>
          </div>
      </div>
  
      

    {% endblock %}

textsummarization/templates/querycmd.html
{% extends "index.html" %}
{% block a %}
    <div class="container-fluid">
        <form method="POST">
          {% csrf_token %}
          <div class="form-group">
                <label for="email">Query</label>
                <input type="text" required class="form-control" name="cmd" id="email">
              </div>
             
              
              <button type="submit" class="btn btn-default btn-success">Submit</button>
        </form>
      </div>
      <div class="container-fluid">
            <div class="form-group">
                <label for="email"> {{A}}</label>
                <table class="table">
                    <thead>
                        <tr>
                            <td>Query</td>
                           
                            <td>Delete</td>
                        </tr>
                    </thead>
                    <tbody>
                      {% for al in data %}
                        <tr>
                          <td>{{al.1}}</td>
                          
                          <td><a href="{% url 'nlpsql:cmdremove' al.0 %}">Remove</a></td>
                        </tr>
                      {% endfor %}
                    </tbody>
                  </table>
              </div>
          </div>
      </div>
  
      

    {% endblock %}

textsummarization/templates/querypage.html
{% extends "index.html" %}
{% block a %}
    <div class="container-fluid">
        <form method="GET">
          {% csrf_token %}
          <div class="form-group">
            <label for="email">News</label>
            <textarea type="text" rows="4" cols="50" required  class="form-control" name="news" id="email">

            </textarea>
          </div>
          
          <button type="submit" class="btn btn-default btn-success">Save</button>
        </form>
      </div>
      <div class="container-fluid">
          <div class="form-group">
              <label for="email"> {{A}}</label>
              <table class="table">
                  <thead>
                   
                  </thead>
                  <tbody>
                    {% for al in data %}
                      <tr>
                        <td>{{al.mainnews}}</td>
                        <td>{{al.summary}}</td>
                        
                      </tr>
                    {% endfor %}
                  </tbody>
                </table>
            </div>
        </div>
    </div>

    {% endblock %}

textsummarization/templates/signup.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login V4</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="{% static 'login/images/icons/favicon.ico' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/fonts/iconic/css/material-design-iconic-font.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/vendor/animate/animate.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'login/vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/vendor/animsition/css/animsition.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'login/vendor/daterangepicker/daterangepicker.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'login/css/main.css' %}">
<!--===============================================================================================-->
</head>
<body>
	
	<div class="limiter">
		<div class="container-login100" style="background-image: url('images/bg-01.jpg');">
			<div class="wrap-login100 p-l-55 p-r-55 p-t-65 p-b-54">
				<form class="login100-form validate-form" method="POST">
                    {% csrf_token %}
					<span class="login100-form-title p-b-49">
						Sign Up
					</span> 

                    <div class="wrap-input100 validate-input m-b-23" data-validate = "Name of user">
						<span class="label-input100">Name</span>
						<input class="input100" type="text" name="name" placeholder="Type your Name">
						<span class="focus-input100" data-symbol="&#xf206;"></span>
                    </div>
                    <div class="wrap-input100 validate-input m-b-23" data-validate = "Address is required">
						<span class="label-input100">Address</span>
						<textarea class="input100" type="text" name="address" placeholder="Address your username">

                        </textarea>
                        
					</div>
					<div class="wrap-input100 validate-input m-b-23" data-validate = "Username is reauired">
						<span class="label-input100">Username</span>
						<input class="input100" type="text" name="username" placeholder="Type your username">
						<span class="focus-input100" data-symbol="&#xf206;"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="Password is required">
						<span class="label-input100">Password</span>
						<input class="input100" type="password" name="pass" placeholder="Type your password">
						<span class="focus-input100" data-symbol="&#xf190;"></span>
					</div>
					
					
                    <div class="text-right p-t-8 p-b-31">
						
					</div>
					<div class="container-login100-form-btn">
						<div class="wrap-login100-form-btn">
							<div class="login100-form-bgbtn"></div>
							<button class="login100-form-btn">
								Sign Up
							</button>
						</div>
					</div>

					<div class="txt1 text-center p-t-54 p-b-20">
						<span>
							<a href="{% url 'usernews:login'  %}" >Login</a>
						</span>
					</div>

					

					<div class="flex-col-c p-t-155">
						<span class="txt1 p-b-17">
							Or Sign Up Using
						</span>

						<a href="#" class="txt2">
							Sign Up
						</a>
					</div>
				</form>
			</div>
		</div>
	</div>
	

	<div id="dropDownSelect1"></div>
	
<!--===============================================================================================-->
	<script src="{% static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/animsition/js/animsition.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/daterangepicker/moment.min.js' %}"></script>
	<script src="{% static 'vendor/daterangepicker/daterangepicker.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/countdowntime/countdowntime.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'js/main.js' %}"></script>

</body>
</html>